image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

customizations:
  vscode:
    extensions:
      - ms-playwright.playwright
    settings:
      docker.showStartPage: false
      extensions.ignoreRecommendations: true
      gitpod.portPrompt: never

tasks:
  - init: |
      chmod +x ./start.sh
      npm install
      npx playwright install chromium
  - command: |
      ./start.sh