image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-preview

tasks:
  - init: |
      chmod +x ./start.sh
      npm install
      npx playwright install chromium
  - command: |
      ./start.sh
